.PHONY: clean All

All:
	@echo "----------Building project:[ Ses2Ej9 - Debug ]----------"
	@cd "Ses2Ej9" && "$(MAKE)" -f  "Ses2Ej9.mk"
clean:
	@echo "----------Cleaning project:[ Ses2Ej9 - Debug ]----------"
	@cd "Ses2Ej9" && "$(MAKE)" -f  "Ses2Ej9.mk" clean
