.PHONY: clean All

All:
	@echo "----------Building project:[ Ses1Ej1 - Debug ]----------"
	@cd "Ejemplo1" && "$(MAKE)" -f  "Ses1Ej1.mk"
clean:
	@echo "----------Cleaning project:[ Ses1Ej1 - Debug ]----------"
	@cd "Ejemplo1" && "$(MAKE)" -f  "Ses1Ej1.mk" clean
