.PHONY: clean All

All:
	@echo "----------Building project:[ Ejemplo1 - Debug ]----------"
	@cd "Ejemplo1" && "$(MAKE)" -f  "Ejemplo1.mk"
clean:
	@echo "----------Cleaning project:[ Ejemplo1 - Debug ]----------"
	@cd "Ejemplo1" && "$(MAKE)" -f  "Ejemplo1.mk" clean
